run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - ineffassign
    - staticcheck
    - unused
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - funlen
    - gochecksumtype
    - maintidx
    - gofmt
    - goimports

linters-settings:
  errcheck:
    exclude-functions:
      - (io.Closer).Close
      - (*database/sql.Rows).Close

  funlen:
    lines: 120
    statements: 120
    ignore-comments: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

    - path: ".*\\.gen\\.go$"
      linters:
        - all

    - path: internal/service/
      text: "G404:"

    - path: internal/database/
      text: "blank-imports:"
