// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	api "github.com/oooooorg/PR-Service/internal/gen"

	mock "github.com/stretchr/testify/mock"

	models "github.com/oooooorg/PR-Service/internal/models"
)

// MockPullRequestService is an autogenerated mock type for the PullRequestService type
type MockPullRequestService struct {
	mock.Mock
}

type MockPullRequestService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPullRequestService) EXPECT() *MockPullRequestService_Expecter {
	return &MockPullRequestService_Expecter{mock: &_m.Mock}
}

// CreatePullRequest provides a mock function with given fields: ctx, req
func (_m *MockPullRequestService) CreatePullRequest(ctx context.Context, req *api.PostPullRequestCreateJSONRequestBody) (*models.PullRequest, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreatePullRequest")
	}

	var r0 *models.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *api.PostPullRequestCreateJSONRequestBody) (*models.PullRequest, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *api.PostPullRequestCreateJSONRequestBody) *models.PullRequest); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *api.PostPullRequestCreateJSONRequestBody) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPullRequestService_CreatePullRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePullRequest'
type MockPullRequestService_CreatePullRequest_Call struct {
	*mock.Call
}

// CreatePullRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - req *api.PostPullRequestCreateJSONRequestBody
func (_e *MockPullRequestService_Expecter) CreatePullRequest(ctx interface{}, req interface{}) *MockPullRequestService_CreatePullRequest_Call {
	return &MockPullRequestService_CreatePullRequest_Call{Call: _e.mock.On("CreatePullRequest", ctx, req)}
}

func (_c *MockPullRequestService_CreatePullRequest_Call) Run(run func(ctx context.Context, req *api.PostPullRequestCreateJSONRequestBody)) *MockPullRequestService_CreatePullRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*api.PostPullRequestCreateJSONRequestBody))
	})
	return _c
}

func (_c *MockPullRequestService_CreatePullRequest_Call) Return(_a0 *models.PullRequest, _a1 error) *MockPullRequestService_CreatePullRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPullRequestService_CreatePullRequest_Call) RunAndReturn(run func(context.Context, *api.PostPullRequestCreateJSONRequestBody) (*models.PullRequest, error)) *MockPullRequestService_CreatePullRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserReviewRequests provides a mock function with given fields: ctx, req
func (_m *MockPullRequestService) GetUserReviewRequests(ctx context.Context, req *api.GetUsersGetReviewParams) ([]*models.PullRequestShort, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetUserReviewRequests")
	}

	var r0 []*models.PullRequestShort
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *api.GetUsersGetReviewParams) ([]*models.PullRequestShort, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *api.GetUsersGetReviewParams) []*models.PullRequestShort); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PullRequestShort)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *api.GetUsersGetReviewParams) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPullRequestService_GetUserReviewRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserReviewRequests'
type MockPullRequestService_GetUserReviewRequests_Call struct {
	*mock.Call
}

// GetUserReviewRequests is a helper method to define mock.On call
//   - ctx context.Context
//   - req *api.GetUsersGetReviewParams
func (_e *MockPullRequestService_Expecter) GetUserReviewRequests(ctx interface{}, req interface{}) *MockPullRequestService_GetUserReviewRequests_Call {
	return &MockPullRequestService_GetUserReviewRequests_Call{Call: _e.mock.On("GetUserReviewRequests", ctx, req)}
}

func (_c *MockPullRequestService_GetUserReviewRequests_Call) Run(run func(ctx context.Context, req *api.GetUsersGetReviewParams)) *MockPullRequestService_GetUserReviewRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*api.GetUsersGetReviewParams))
	})
	return _c
}

func (_c *MockPullRequestService_GetUserReviewRequests_Call) Return(_a0 []*models.PullRequestShort, _a1 error) *MockPullRequestService_GetUserReviewRequests_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPullRequestService_GetUserReviewRequests_Call) RunAndReturn(run func(context.Context, *api.GetUsersGetReviewParams) ([]*models.PullRequestShort, error)) *MockPullRequestService_GetUserReviewRequests_Call {
	_c.Call.Return(run)
	return _c
}

// MergePullRequest provides a mock function with given fields: ctx, req
func (_m *MockPullRequestService) MergePullRequest(ctx context.Context, req *api.PostPullRequestMergeJSONRequestBody) (*models.PullRequest, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for MergePullRequest")
	}

	var r0 *models.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *api.PostPullRequestMergeJSONRequestBody) (*models.PullRequest, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *api.PostPullRequestMergeJSONRequestBody) *models.PullRequest); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *api.PostPullRequestMergeJSONRequestBody) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPullRequestService_MergePullRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MergePullRequest'
type MockPullRequestService_MergePullRequest_Call struct {
	*mock.Call
}

// MergePullRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - req *api.PostPullRequestMergeJSONRequestBody
func (_e *MockPullRequestService_Expecter) MergePullRequest(ctx interface{}, req interface{}) *MockPullRequestService_MergePullRequest_Call {
	return &MockPullRequestService_MergePullRequest_Call{Call: _e.mock.On("MergePullRequest", ctx, req)}
}

func (_c *MockPullRequestService_MergePullRequest_Call) Run(run func(ctx context.Context, req *api.PostPullRequestMergeJSONRequestBody)) *MockPullRequestService_MergePullRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*api.PostPullRequestMergeJSONRequestBody))
	})
	return _c
}

func (_c *MockPullRequestService_MergePullRequest_Call) Return(_a0 *models.PullRequest, _a1 error) *MockPullRequestService_MergePullRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPullRequestService_MergePullRequest_Call) RunAndReturn(run func(context.Context, *api.PostPullRequestMergeJSONRequestBody) (*models.PullRequest, error)) *MockPullRequestService_MergePullRequest_Call {
	_c.Call.Return(run)
	return _c
}

// ReassignReviewer provides a mock function with given fields: ctx, req
func (_m *MockPullRequestService) ReassignReviewer(ctx context.Context, req *api.PostPullRequestReassignJSONRequestBody) (*models.PullRequest, string, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ReassignReviewer")
	}

	var r0 *models.PullRequest
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *api.PostPullRequestReassignJSONRequestBody) (*models.PullRequest, string, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *api.PostPullRequestReassignJSONRequestBody) *models.PullRequest); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *api.PostPullRequestReassignJSONRequestBody) string); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *api.PostPullRequestReassignJSONRequestBody) error); ok {
		r2 = rf(ctx, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockPullRequestService_ReassignReviewer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReassignReviewer'
type MockPullRequestService_ReassignReviewer_Call struct {
	*mock.Call
}

// ReassignReviewer is a helper method to define mock.On call
//   - ctx context.Context
//   - req *api.PostPullRequestReassignJSONRequestBody
func (_e *MockPullRequestService_Expecter) ReassignReviewer(ctx interface{}, req interface{}) *MockPullRequestService_ReassignReviewer_Call {
	return &MockPullRequestService_ReassignReviewer_Call{Call: _e.mock.On("ReassignReviewer", ctx, req)}
}

func (_c *MockPullRequestService_ReassignReviewer_Call) Run(run func(ctx context.Context, req *api.PostPullRequestReassignJSONRequestBody)) *MockPullRequestService_ReassignReviewer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*api.PostPullRequestReassignJSONRequestBody))
	})
	return _c
}

func (_c *MockPullRequestService_ReassignReviewer_Call) Return(_a0 *models.PullRequest, _a1 string, _a2 error) *MockPullRequestService_ReassignReviewer_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockPullRequestService_ReassignReviewer_Call) RunAndReturn(run func(context.Context, *api.PostPullRequestReassignJSONRequestBody) (*models.PullRequest, string, error)) *MockPullRequestService_ReassignReviewer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPullRequestService creates a new instance of MockPullRequestService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPullRequestService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPullRequestService {
	mock := &MockPullRequestService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
