// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	api "github.com/oooooorg/PR-Service/internal/gen"

	mock "github.com/stretchr/testify/mock"

	models "github.com/oooooorg/PR-Service/internal/models"
)

// MockTeamService is an autogenerated mock type for the TeamService type
type MockTeamService struct {
	mock.Mock
}

type MockTeamService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamService) EXPECT() *MockTeamService_Expecter {
	return &MockTeamService_Expecter{mock: &_m.Mock}
}

// CreateTeam provides a mock function with given fields: ctx, team
func (_m *MockTeamService) CreateTeam(ctx context.Context, team *api.Team) (*models.Team, error) {
	ret := _m.Called(ctx, team)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeam")
	}

	var r0 *models.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *api.Team) (*models.Team, error)); ok {
		return rf(ctx, team)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *api.Team) *models.Team); ok {
		r0 = rf(ctx, team)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *api.Team) error); ok {
		r1 = rf(ctx, team)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamService_CreateTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTeam'
type MockTeamService_CreateTeam_Call struct {
	*mock.Call
}

// CreateTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - team *api.Team
func (_e *MockTeamService_Expecter) CreateTeam(ctx interface{}, team interface{}) *MockTeamService_CreateTeam_Call {
	return &MockTeamService_CreateTeam_Call{Call: _e.mock.On("CreateTeam", ctx, team)}
}

func (_c *MockTeamService_CreateTeam_Call) Run(run func(ctx context.Context, team *api.Team)) *MockTeamService_CreateTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*api.Team))
	})
	return _c
}

func (_c *MockTeamService_CreateTeam_Call) Return(_a0 *models.Team, _a1 error) *MockTeamService_CreateTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamService_CreateTeam_Call) RunAndReturn(run func(context.Context, *api.Team) (*models.Team, error)) *MockTeamService_CreateTeam_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeam provides a mock function with given fields: ctx, req
func (_m *MockTeamService) GetTeam(ctx context.Context, req *api.GetTeamGetParams) (*models.Team, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetTeam")
	}

	var r0 *models.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *api.GetTeamGetParams) (*models.Team, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *api.GetTeamGetParams) *models.Team); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *api.GetTeamGetParams) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamService_GetTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeam'
type MockTeamService_GetTeam_Call struct {
	*mock.Call
}

// GetTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - req *api.GetTeamGetParams
func (_e *MockTeamService_Expecter) GetTeam(ctx interface{}, req interface{}) *MockTeamService_GetTeam_Call {
	return &MockTeamService_GetTeam_Call{Call: _e.mock.On("GetTeam", ctx, req)}
}

func (_c *MockTeamService_GetTeam_Call) Run(run func(ctx context.Context, req *api.GetTeamGetParams)) *MockTeamService_GetTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*api.GetTeamGetParams))
	})
	return _c
}

func (_c *MockTeamService_GetTeam_Call) Return(_a0 *models.Team, _a1 error) *MockTeamService_GetTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamService_GetTeam_Call) RunAndReturn(run func(context.Context, *api.GetTeamGetParams) (*models.Team, error)) *MockTeamService_GetTeam_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTeamService creates a new instance of MockTeamService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamService {
	mock := &MockTeamService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
