// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	api "github.com/oooooorg/PR-Service/internal/gen"

	mock "github.com/stretchr/testify/mock"

	models "github.com/oooooorg/PR-Service/internal/models"
)

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// SetUserActive provides a mock function with given fields: ctx, req
func (_m *MockUserService) SetUserActive(ctx context.Context, req *api.PostUsersSetIsActiveJSONRequestBody) (*models.User, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SetUserActive")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *api.PostUsersSetIsActiveJSONRequestBody) (*models.User, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *api.PostUsersSetIsActiveJSONRequestBody) *models.User); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *api.PostUsersSetIsActiveJSONRequestBody) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_SetUserActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserActive'
type MockUserService_SetUserActive_Call struct {
	*mock.Call
}

// SetUserActive is a helper method to define mock.On call
//   - ctx context.Context
//   - req *api.PostUsersSetIsActiveJSONRequestBody
func (_e *MockUserService_Expecter) SetUserActive(ctx interface{}, req interface{}) *MockUserService_SetUserActive_Call {
	return &MockUserService_SetUserActive_Call{Call: _e.mock.On("SetUserActive", ctx, req)}
}

func (_c *MockUserService_SetUserActive_Call) Run(run func(ctx context.Context, req *api.PostUsersSetIsActiveJSONRequestBody)) *MockUserService_SetUserActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*api.PostUsersSetIsActiveJSONRequestBody))
	})
	return _c
}

func (_c *MockUserService_SetUserActive_Call) Return(_a0 *models.User, _a1 error) *MockUserService_SetUserActive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_SetUserActive_Call) RunAndReturn(run func(context.Context, *api.PostUsersSetIsActiveJSONRequestBody) (*models.User, error)) *MockUserService_SetUserActive_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
